name: PR Preview
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.51.2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Build site
        run: mkdocs build -d ./site/preview/${{ github.event.number }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: true
          destination_dir: .

      - name: Get Pages URL
        id: pages-url
        uses: actions/github-script@v6
        with:
          script: |
            const pages = await github.rest.repos.getPages({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return pages.data.html_url;

      - name: Comment PR
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          github-comment hide
          github-comment post -template "🚀 Preview Site: ${{ steps.pages-url.outputs.result }}preview/${{ github.event.number }}/"
      - name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          github-comment post -template "higehigehigehige"
